export default () => ({
  authUser: null,
  session: {},
  credential: {},
  dataSource: [],
  users: [],
  token: '',
  thoughts: [],
  alerts: [],
  dataSavingTime: [],
  dataSet: [],
  devices: [],
  values: [
    {
      key: 'heartRateByDay',
      name: 'Frecuencia Cardiaca',
      indicator: 'heartRate',
      indicatorUnit: 'lat/min',
      dataTypeName: 'com.google.heart_rate.bpm',
      type: 'healthPhysical',
      frequency: 'day',
      maxSalud: 120,
      minSalud: 60,
      maxAcept: 200,
      minAcept: 50,
      weight: 3,
      weightPercentage: 0.5
    },
    {
      key: 'stepByDay',
      name: 'Pasos',
      indicator: 'step',
      indicatorUnit: 'cal',
      dataTypeName: 'com.google.step_count.delta',
      type: 'healthPhysical',
      frequency: 'day',
      maxSalud: 730,
      minSalud: 365,
      maxAcept: 1460,
      minAcept: 180,
      weight: 1,
      weightPercentage: 0.17
    },
    {
      key: 'caloriesBurnedByDay',
      name: 'Calorias quemadas',
      indicator: 'caloriesBurned',
      indicatorUnit: 'cal',
      dataTypeName: 'com.google.calories.expended',
      type: 'healthPhysical',
      frequency: 'day',
      maxSalud: 100,
      minSalud: 50,
      maxAcept: 200,
      minAcept: 25,
      weight: 1,
      weightPercentage: 0.17
    },
    {
      key: 'sleepByDay',
      name: 'Sueño',
      indicator: 'sleep',
      indicatorUnit: 'horas',
      dataTypeName: 'com.google.sleep.segment',
      type: 'healthMental',
      frequency: 'day',
      maxSalud: 200,
      minSalud: 100,
      maxAcept: 400,
      minAcept: 50,
      weight: 1,
      weightPercentage: 0.17
    },
    {
      key: 'sleepDeepByDay',
      name: 'Sueño Profundo',
      indicator: 'sleepDeep',
      indicatorUnit: 'horas',
      dataTypeName: 'app.web.hear-my-health.sleep.deep',
      type: 'healthMental',
      frequency: 'day',
      maxSalud: 100,
      minSalud: 50,
      maxAcept: 200,
      minAcept: 25,
      weight: 1,
      weightPercentage: 0.17
    },
    {
      key: 'moodByDay',
      name: 'Estado de animo',
      indicator: 'mood',
      indicatorUnit: 'horas',
      dataTypeName: 'app.web.hear-my-health.mood.segment',
      type: 'healthMental',
      frequency: 'day',
      maxSalud: 4,
      minSalud: 3,
      maxAcept: 2,
      minAcept: 1,
      weight: 1,
      weightPercentage: 0.17
    }
  ]
})
